[package]
name = "gix-forge"
version = "0.1.0"
edition = "2024"

[dependencies]
gix.workspace = true
gix-comment.workspace = true
gix-store.workspace = true
gix-query.workspace = true
facet.workspace = true
facet-value.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
test-support = { path = "../test-support" }
